version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: douyin-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: douyin
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "13306:3306"


  redis:
    image: redis:latest
    container_name: douyin-redis
    restart: always
    environment:
      REDIS_PASSWORD: 12345
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    ports:
      - "16379:6379"

  etcd:
    image: bitnami/etcd:latest
    container_name: douyin-etcd
    restart: always
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    expose:
      - "2379"
      - "2380"

    volumes:
      - etcd_data:/bitnami
    ports:
      - "2379:2379"

  douyin-micro:
    image: guanjunyou/douyin-micro:v1.0
    container_name: douyin-micro
    restart: always
    ports:
      - "18080:8080"
    depends_on:
      - mysql
      - redis
      - etcd

  prometheus:
    image: prom/prometheus:latest
    container_name: douyin-prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules:/etc/prometheus/alert.rules
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - '9090'
    depends_on:
      - douyin-micro
    ports:
      - "19090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: douyin-grafana
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    ports:
      - '13000:3000'
      - '8060:8060'
      - '8085:8085'


volumes:
  mysql_data:
  redis_data:
  etcd_data:
  grafana_data:
  prometheus_data: